import { useState } from "react";
import {
  Routes,
  Route,
  NavLink,
  useLocation,
  useNavigate,
} from "react-router-dom";

import RiskDemo from "./pages/RiskDemo";
import RecommendationDemo from "./pages/RecommendationDemo";
import CreateQuiz from "./pages/CreateQuiz";
import QuizList from "./pages/QuizList";
import TakeQuiz from "./pages/TakeQuiz";
import StruggleDashboard from "./pages/StruggleDashboard";
import QuizLevels from "./pages/QuizLevels";
import PdfUpload from "./pages/PdfUpload";
import Chat from "./pages/Chat";
import GlobalReminders from "./componets/GlobalReminders";
import AdminAnnouncements from "./pages/AdminAnnouncements";
import UserAnnouncements from "./pages/UserAnnouncements";
import AdminFeedback from "./pages/AdminFeedback";

function Layout() {
  const [isChatOpen, setIsChatOpen] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();

  const path = location.pathname || "/";

  let headerTitle = "Student risk analytics";
  let headerSubtitle =
    "Demo how AcademiGuard scores academic risk per student.";

  if (path === "/" || path === "/risk") {
    headerTitle = "Student risk analytics";
    headerSubtitle = "Demo how AcademiGuard scores academic risk per student.";
  } else if (path === "/announcements") {
    headerTitle = "Announcements & reminders";
    headerSubtitle =
      "Read the latest announcements and any active reminders from your instructors.";
  } else if (path === "/admin/announcements") {
    headerTitle = "Manage announcements";
    headerSubtitle =
      "Create and review announcements that will be shown to students.";
  } else if (path === "/admin/upload") {
    headerTitle = "Knowledge base / PDF ingestion";
    headerSubtitle = "Manage the documents used by the chatbot for answers.";
  } else if (path === "/admin/feedback") {
    headerTitle = "Chatbot feedback & reviews";
    headerSubtitle =
      "Monitor chatbot ratings, read feedback, and clean up inappropriate reviews.";
  } else if (path === "/quizzes") {
    headerTitle = "Available quizzes";
    headerSubtitle = "Browse and attempt available quizzes.";
  } else if (path === "/create-quiz") {
    headerTitle = "Create quiz";
    headerSubtitle = "Design and publish new quizzes for students.";
  } else if (path === "/levels") {
    headerTitle = "Quiz levels";
    headerSubtitle = "Track student progress across quiz levels.";
  } else if (path.startsWith("/quiz/")) {
    headerTitle = "Take quiz";
    headerSubtitle = "Answer questions and complete your quiz attempt.";
  } else if (path === "/struggle") {
    headerTitle = "Struggle dashboard";
    headerSubtitle =
      "Review struggling skills and risk indicators for students.";
  } else if (path === "/recommendation") {
    headerTitle = "Recommendation demo";
    headerSubtitle = "Explore the recommendations generated by the model.";
  }

  const hideReminders = path.startsWith("/admin/");

  const navLinkBase =
    "mt-1 w-full flex items-center justify-between px-3 py-2 rounded-lg text-left text-xs font-medium transition-colors";

  const navLinkClass = ({ isActive }) =>
    `${navLinkBase} ${
      isActive
        ? "bg-slate-800 text-white shadow-sm ring-1 ring-slate-700/60"
        : "text-slate-200 hover:bg-slate-800/70"
    }`;

  return (
    <div className="min-h-screen bg-slate-900 flex text-slate-900">
      {/* Sidebar - stays visible while scrolling */}
      <aside className="w-64 bg-slate-950/95 text-slate-100 flex flex-col border-r border-slate-800/80 sticky top-0 h-screen">
        <div className="px-5 py-4 border-b border-slate-800/80 bg-gradient-to-r from-slate-950 to-slate-900">
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-xl bg-blue-500 flex items-center justify-center text-xs font-bold shadow-sm">
              AG
            </div>
            <div>
              <h1 className="text-sm font-semibold tracking-tight">
                AcademiGuard
              </h1>
              <p className="mt-0.5 text-[11px] text-slate-400">
                Academic integrity & risk assistant
              </p>
            </div>
          </div>
        </div>

        <nav className="flex-1 px-3 py-4 space-y-6 text-sm">
          <div>
            <p className="px-2 text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Main
            </p>
            <NavLink to="/risk" className={navLinkClass}>
              <span>Risk demo</span>
            </NavLink>
            <NavLink to="/announcements" className={navLinkClass}>
              <span>Announcements</span>
            </NavLink>
            <NavLink to="/levels" className={navLinkClass}>
              <span>Quiz levels</span>
            </NavLink>
            <NavLink to="/quizzes" className={navLinkClass}>
              <span>Quiz list</span>
            </NavLink>
          </div>

          <div>
            <p className="px-2 text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Admin
            </p>
            <NavLink to="/admin/upload" className={navLinkClass}>
              <span>Upload PDFs</span>
            </NavLink>
            <NavLink to="/admin/announcements" className={navLinkClass}>
              <span>Manage announcements</span>
            </NavLink>
            <NavLink to="/admin/feedback" className={navLinkClass}>
              <span>Chatbot feedback</span>
            </NavLink>
            <NavLink to="/create-quiz" className={navLinkClass}>
              <span>Create quiz</span>
            </NavLink>
          </div>
        </nav>

        <div className="px-5 py-3 border-t border-slate-800/80 text-[11px] text-slate-500/80">
          <p className="leading-snug">
            Chatbot is available on every page via the
            <span className="font-semibold text-slate-300">
              {" "}
              Ask AcademiGuard
            </span>
            &nbsp;button.
          </p>
        </div>
      </aside>

      {/* Main content area */}
      <div className="flex-1 flex flex-col relative bg-slate-100/90">
        <header className="bg-white/95 backdrop-blur border-b border-slate-200">
          <div className="max-w-5xl mx-auto px-6 py-3 flex items-center justify-between">
            <div>
              <h2 className="text-sm font-semibold text-slate-900">
                {headerTitle}
              </h2>
              <p className="mt-0.5 text-[11px] text-slate-500">
                {headerSubtitle}
              </p>
            </div>
            <div className="flex items-center gap-3 text-[11px]">
              <button
                type="button"
                onClick={() => navigate("/announcements")}
                className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-600 hover:bg-slate-100 hover:text-slate-900 shadow-sm"
                aria-label="Open announcements"
              >
                <span className="text-base">🔔</span>
              </button>
              <div className="hidden sm:flex items-center gap-2">
                <span className="inline-flex items-center rounded-full bg-emerald-50 px-2 py-0.5 text-emerald-700 border border-emerald-200">
                  ● Online
                </span>
                <span className="text-slate-400">ML service</span>
              </div>
            </div>
          </div>
        </header>

        <main className="flex-1 max-w-5xl mx-auto w-full px-6 py-6">
          {!hideReminders && (
            <GlobalReminders
              onReminderClick={() => navigate("/announcements")}
            />
          )}
          <Routes>
            <Route path="/" element={<RiskDemo />} />
            <Route path="/risk" element={<RiskDemo />} />
            <Route path="/recommendation" element={<RecommendationDemo />} />
            <Route path="/announcements" element={<UserAnnouncements />} />
            <Route
              path="/admin/announcements"
              element={<AdminAnnouncements />}
            />
            <Route path="/admin/upload" element={<PdfUpload />} />
            <Route path="/admin/feedback" element={<AdminFeedback />} />
            <Route path="/quizzes" element={<QuizList />} />
            <Route path="/create-quiz" element={<CreateQuiz />} />
            <Route path="/levels" element={<QuizLevels />} />
            <Route path="/quiz/:id" element={<TakeQuiz />} />
            <Route path="/struggle" element={<StruggleDashboard />} />
          </Routes>
        </main>

        {/* Floating chatbot button & panel */}
        {!isChatOpen && (
          <button
            onClick={() => setIsChatOpen(true)}
            className="fixed bottom-8 right-8 z-40 relative w-20 h-20 rounded-full transition-all duration-300 ease-out hover:scale-125 focus:outline-none group"
            title="💬 AI Chatbot - Ask AcademiGuard"
          >
            {/* Animated background rings */}
            <span className="absolute inset-0 rounded-full bg-gradient-to-br from-purple-400 to-indigo-400 opacity-30 animate-pulse blur-md"></span>

            {/* Outer rotating ring */}
            <span
              className="absolute -inset-2 rounded-full border-2 border-transparent border-t-purple-400 border-r-indigo-500 opacity-60 animate-spin"
              style={{ animationDuration: "3s" }}
            ></span>

            {/* Middle pulsing ring */}
            <span className="absolute -inset-1 rounded-full border-2 border-purple-300/40 animate-pulse"></span>

            {/* Main button background */}
            <span className="absolute inset-0 rounded-full bg-gradient-to-br from-purple-600 via-purple-500 to-indigo-600 shadow-2xl shadow-purple-600/70"></span>

            {/* Inner glow */}
            <span className="absolute inset-1 rounded-full bg-gradient-to-tr from-purple-500/20 to-indigo-400/20"></span>

            {/* Bouncing notification badge */}
            <span
              className="absolute -top-2 -right-2 inline-flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-red-500 to-pink-600 text-2xl shadow-xl shadow-red-500/60 animate-bounce border-4 border-white"
              style={{ boxShadow: "0 0 25px rgba(239, 68, 68, 0.9)" }}
            >
              💬
            </span>

            {/* Main icon container */}
            <div className="absolute inset-0 flex items-center justify-center">
              {/* Large prominent chat icon */}
              <svg
                className="w-10 h-10 text-white drop-shadow-xl animate-bounce"
                style={{ animationDelay: "0.2s" }}
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
                />
              </svg>
            </div>

            {/* Hover shine effect */}
            <span className="absolute inset-0 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-gradient-to-tr from-white/20 to-transparent"></span>
          </button>
        )}

        {isChatOpen && (
          <div className="fixed bottom-5 right-5 sm:bottom-6 sm:right-6 z-50 w-[92vw] max-w-md">
            <Chat onClose={() => setIsChatOpen(false)} />
          </div>
        )}
      </div>
    </div>
  );
}

export default Layout;
