import { useState } from "react";
import {
  Routes,
  Route,
  NavLink,
  useLocation,
  useNavigate,
} from "react-router-dom";

import RiskDemo from "./pages/RiskDemo";
import RecommendationDemo from "./pages/RecommendationDemo";
import CreateQuiz from "./pages/CreateQuiz";
import QuizList from "./pages/QuizList";
import TakeQuiz from "./pages/TakeQuiz";
import StruggleDashboard from "./pages/StruggleDashboard";
import QuizLevels from "./pages/QuizLevels";
import PdfUpload from "./pages/PdfUpload";
import Chat from "./pages/Chat";
import GlobalReminders from "./componets/GlobalReminders";
import AdminAnnouncements from "./pages/AdminAnnouncements";
import UserAnnouncements from "./pages/UserAnnouncements";
import AdminFeedback from "./pages/AdminFeedback";

function Layout() {
  const [isChatOpen, setIsChatOpen] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();

  const path = location.pathname || "/";

  let headerTitle = "Student risk analytics";
  let headerSubtitle =
    "Demo how AcademiGuard scores academic risk per student.";

  if (path === "/" || path === "/risk") {
    headerTitle = "Student risk analytics";
    headerSubtitle =
      "Demo how AcademiGuard scores academic risk per student.";
  } else if (path === "/announcements") {
    headerTitle = "Announcements & reminders";
    headerSubtitle =
      "Read the latest announcements and any active reminders from your instructors.";
  } else if (path === "/admin/announcements") {
    headerTitle = "Manage announcements";
    headerSubtitle =
      "Create and review announcements that will be shown to students.";
  } else if (path === "/admin/upload") {
    headerTitle = "Knowledge base / PDF ingestion";
    headerSubtitle = "Manage the documents used by the chatbot for answers.";
  } else if (path === "/admin/feedback") {
    headerTitle = "Chatbot feedback & reviews";
    headerSubtitle =
      "Monitor chatbot ratings, read feedback, and clean up inappropriate reviews.";
  } else if (path === "/quizzes") {
    headerTitle = "Available quizzes";
    headerSubtitle = "Browse and attempt available quizzes.";
  } else if (path === "/create-quiz") {
    headerTitle = "Create quiz";
    headerSubtitle = "Design and publish new quizzes for students.";
  } else if (path === "/levels") {
    headerTitle = "Quiz levels";
    headerSubtitle = "Track student progress across quiz levels.";
  } else if (path.startsWith("/quiz/")) {
    headerTitle = "Take quiz";
    headerSubtitle = "Answer questions and complete your quiz attempt.";
  } else if (path === "/struggle") {
    headerTitle = "Struggle dashboard";
    headerSubtitle =
      "Review struggling skills and risk indicators for students.";
  } else if (path === "/recommendation") {
    headerTitle = "Recommendation demo";
    headerSubtitle = "Explore the recommendations generated by the model.";
  }

  const hideReminders = path.startsWith("/admin/");

  const navLinkBase =
    "mt-1 w-full flex items-center justify-between px-3 py-2 rounded-lg text-left text-xs font-medium transition-colors";

  const navLinkClass = ({ isActive }) =>
    `${navLinkBase} ${
      isActive
        ? "bg-slate-800 text-white shadow-sm ring-1 ring-slate-700/60"
        : "text-slate-200 hover:bg-slate-800/70"
    }`;

  return (
    <div className="min-h-screen bg-slate-900 flex text-slate-900">
      {/* Sidebar - stays visible while scrolling */}
      <aside className="w-64 bg-slate-950/95 text-slate-100 flex flex-col border-r border-slate-800/80 sticky top-0 h-screen">
        <div className="px-5 py-4 border-b border-slate-800/80 bg-gradient-to-r from-slate-950 to-slate-900">
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-xl bg-blue-500 flex items-center justify-center text-xs font-bold shadow-sm">
              AG
            </div>
            <div>
              <h1 className="text-sm font-semibold tracking-tight">
                AcademiGuard
              </h1>
              <p className="mt-0.5 text-[11px] text-slate-400">
                Academic integrity & risk assistant
              </p>
            </div>
          </div>
        </div>

        <nav className="flex-1 px-3 py-4 space-y-6 text-sm">
          <div>
            <p className="px-2 text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Main
            </p>
            <NavLink to="/risk" className={navLinkClass}>
              <span>Risk demo</span>
            </NavLink>
            <NavLink to="/announcements" className={navLinkClass}>
              <span>Announcements</span>
            </NavLink>
            <NavLink to="/levels" className={navLinkClass}>
              <span>Quiz levels</span>
            </NavLink>
            <NavLink to="/quizzes" className={navLinkClass}>
              <span>Quiz list</span>
            </NavLink>
          </div>

          <div>
            <p className="px-2 text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Admin
            </p>
            <NavLink to="/admin/upload" className={navLinkClass}>
              <span>Upload PDFs</span>
            </NavLink>
            <NavLink to="/admin/announcements" className={navLinkClass}>
              <span>Manage announcements</span>
            </NavLink>
            <NavLink to="/admin/feedback" className={navLinkClass}>
              <span>Chatbot feedback</span>
            </NavLink>
            <NavLink to="/create-quiz" className={navLinkClass}>
              <span>Create quiz</span>
            </NavLink>
          </div>
        </nav>

        <div className="px-5 py-3 border-t border-slate-800/80 text-[11px] text-slate-500/80">
          <p className="leading-snug">
            Chatbot is available on every page via the
            <span className="font-semibold text-slate-300">
              {" "}
              Ask AcademiGuard
            </span>
            &nbsp;button.
          </p>
        </div>
      </aside>

      {/* Main content area */}
      <div className="flex-1 flex flex-col relative bg-slate-100/90">
        <header className="bg-white/95 backdrop-blur border-b border-slate-200">
          <div className="max-w-5xl mx-auto px-6 py-3 flex items-center justify-between">
            <div>
              <h2 className="text-sm font-semibold text-slate-900">
                {headerTitle}
              </h2>
              <p className="mt-0.5 text-[11px] text-slate-500">
                {headerSubtitle}
              </p>
            </div>
            <div className="flex items-center gap-3 text-[11px]">
              <button
                type="button"
                onClick={() => navigate("/announcements")}
                className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-600 hover:bg-slate-100 hover:text-slate-900 shadow-sm"
                aria-label="Open announcements"
              >
                <span className="text-base">🔔</span>
              </button>
              <div className="hidden sm:flex items-center gap-2">
                <span className="inline-flex items-center rounded-full bg-emerald-50 px-2 py-0.5 text-emerald-700 border border-emerald-200">
                  ● Online
                </span>
                <span className="text-slate-400">ML service</span>
              </div>
            </div>
          </div>
        </header>

        <main className="flex-1 max-w-5xl mx-auto w-full px-6 py-6">
          {!hideReminders && (
            <GlobalReminders
              onReminderClick={() => navigate("/announcements")}
            />
          )}
          <Routes>
            <Route path="/" element={<RiskDemo />} />
            <Route path="/risk" element={<RiskDemo />} />
            <Route path="/recommendation" element={<RecommendationDemo />} />
            <Route path="/announcements" element={<UserAnnouncements />} />
            <Route
              path="/admin/announcements"
              element={<AdminAnnouncements />}
            />
            <Route path="/admin/upload" element={<PdfUpload />} />
            <Route path="/admin/feedback" element={<AdminFeedback />} />
            <Route path="/quizzes" element={<QuizList />} />
            <Route path="/create-quiz" element={<CreateQuiz />} />
            <Route path="/levels" element={<QuizLevels />} />
            <Route path="/quiz/:id" element={<TakeQuiz />} />
            <Route path="/struggle" element={<StruggleDashboard />} />
          </Routes>
        </main>

        {/* Floating chatbot button & panel */}
        {!isChatOpen && (
          <button
            onClick={() => setIsChatOpen(true)}
            className="fixed bottom-5 right-5 z-40 inline-flex items-center gap-2 rounded-full bg-blue-600 px-4 py-2 text-xs font-semibold text-white shadow-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-300"
          >
            <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-blue-500 text-[11px] font-bold">
              AI
            </span>
            <span>Ask AcademiGuard</span>
          </button>
        )}

        {isChatOpen && (
          <div className="fixed bottom-5 right-5 sm:bottom-6 sm:right-6 z-50 w-[92vw] max-w-md">
            <Chat onClose={() => setIsChatOpen(false)} />
          </div>
        )}
      </div>
    </div>
  );
}

export default Layout;
